clusters:
- name: uddhao-dpc-cp
  server: http://cluster-uddhao-dpc:8001
  env: test1
- name: test-dpc-cp
  server: http://cluster-test-dpc:8001
  env: test2
- name: test-tara-cp
  server: http://cluster-test-tara:8001
  env: test3
